# Generated by Django 3.1.3 on 2020-11-18 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='Creditos',
            new_name='Horas',
        ),
    ]
